### PR TITLE
Task contact

### PR DESCRIPTION
**Pull request by DevUsman-18**
task-contact completed plus media queries for site

### CODE REVIEW

**Review by lilyboughton — CHANGES_REQUESTED** [review]
Implement another breakpoint to account for 1000px - 760px

**Comment by Reductito** [comment]
Does the code do what it's supposed to? Yes, contact links work and the media queries correctly collapse the elements at the right screen sizes.

Consistency - yes, always uses either px or % values for width/height etc, uses double quote marks for all classes, uses flex consistently 

Indentation is correct

Comment:
Perhaps consider adding a a small margin between the project pictures and the text; when I make the screen small but not small enough to trigger the mid-size screen media query the text sometimes sits right next to the image like so: 

Screenshot 2021-09-08 at 12 40 22

**Comment by Reductito** [comment]
Screenshot 2021-09-08 at 13 35 31

**Comment by Reductito** [comment]
Project text spacing and html warnings fixed, all looking good!

**Pull request merged**
